version: '3.8'

services:
  # 1. The PostgreSQL Database
  db:
    image: postgres:15
    container_name: nifty100_db
    restart: always
    environment:
      POSTGRES_USER: nifty_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: nifty100_warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. pgAdmin (A visual dashboard to look at your database)
  pgadmin:
    image: dpage/pgadmin4
    container_name: nifty100_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nifty.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: